#pragma once

// Compatibility umbrella. New code should include the narrow header that owns
// the type it uses.
#include "hbfsim/common/address.h"
#include "hbfsim/common/types.h"
#include "hbfsim/config/config.h"
#include "hbfsim/controller/base_die.h"
#include "hbfsim/controller/interconnect.h"
#include "hbfsim/controller/interconnect_model.h"
#include "hbfsim/controller/media_scheduler.h"
#include "hbfsim/extension/copy_engine.h"
#include "hbfsim/frontend/trace.h"
#include "hbfsim/hbf_system.h"
#include "hbfsim/kernel/event.h"
#include "hbfsim/management/host_gc.h"
#include "hbfsim/management/refresh.h"
#include "hbfsim/management/reduced_capacity.h"
#include "hbfsim/management/wear_level.h"
#include "hbfsim/mapping/mapper.h"
#include "hbfsim/mapping/stripe_mapping.h"
#include "hbfsim/media/nand_media.h"
#include "hbfsim/media/read_cache.h"
#include "hbfsim/media/reliability.h"
#include "hbfsim/media/state.h"
#include "hbfsim/media/topology.h"
#include "hbfsim/protocol/axi.h"
#include "hbfsim/protocol/channel.h"
#include "hbfsim/protocol/dlu.h"
#include "hbfsim/protocol/frontend.h"
#include "hbfsim/protocol/request.h"
#include "hbfsim/protocol/status.h"
#include "hbfsim/protocol/validator.h"
#include "hbfsim/simulator.h"
#include "hbfsim/stats/stats.h"
